name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: 
  push:
    branches:
      - main
      - develop
      - master
      
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: 18
      
      - name: Install dependencies
        run: npm ci

      - name: Generate Release
        run: npx semantic-release
